name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: make
      run: make universal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        path: ./
